### ISSUE TITLE
Seminar 15

### ISSUE THREAD

**Issue by notmandatory** [NashBitDevs/nashbitdevs.org#18]
January 16, 2023 @ 5:00p

Add comments below to add or comment on topics for [Socratic Seminar 15](https://nashbitdevs.org/socratic-seminar-15/). See also ["Where to Find Topics for Future Seminars"](https://nashbitdevs.org/about/find-topics/).

Categories:

* Events
* News
* New Work/Research
* Bitcoin Projects
* Lightning Projects

**Comment by notmandatory** [comment]
Research

- [Bitcoin Covenants Wiki](https://covenants.info/overview/summary/)

**Comment by reez** [comment]
**Lightning**

- [Amboss introduces Ghost Address](https://twitter.com/ambosstech/status/1737880662617583826)
- Phoenix Wallet [2.1.0 Liquidity Ads](https://github.com/ACINQ/phoenix/releases/tag/android-v2.1.0)
- LDK Node [0.2.0 release](https://github.com/lightningdevkit/ldk-node/releases/tag/v0.2.0)
- [The challenges of developing non-custodial lightning on mobile](https://lightningdevkit.org/blog/the-challenges-of-developing-non-custodial-lightning-on-mobile/) by Matt Corallo
- [Rethinking Lightning](https://stacker.news/items/379225)


**Bitcoin**

- [Mempool Goggles](https://nitter.net/mempool/status/1736700022350090400) from mempool.space


**News**

- [The Bitcoin Dev Project](https://bitcoindevs.xyz)
- Open Sats
  - [Third Wave of Bitcoin Grants](https://opensats.org/blog/bitcoin-grants-december-2023)
  - [Fourth Wave of Nostr Grants](https://opensats.org/blog/nostr-grants-december-2023?ref=nobsbitcoin.com)
  - [Long-Term Support For Tobin Harding](https://opensats.org/blog/tobin-harding-receives-lts-grant-for-rust-bitcoin)
  - [OpenSats' 2023 Year in Review](https://opensats.org/blog/2023-year-in-review)
- [Human Rights Foundation announced its most recent round of Bitcoin Development Fund grants](https://bitcoinmagazine.com/business/human-rights-foundation-grants-500000-to-18-bitcoin-projects-worldwide)
- [Vinteum extends brrrunog and Erik17192799 funding for another year](https://twitter.com/vinteum_org/status/1737880749276098683?s=12&t=tjvL-eINwWwpULIItNU3KA)

**Comment by willowenss** [comment]
Not in Nashville right now, but a topic I think is relevant:
Are BTC spot ETFs at high risk because Coinbase is listed as custodian for almost all the ETFs?
Should the custodians be more 'decentralized'? Is it a big problem that Coinbase is effectively 'running the show'? Or is this okay? Would love to hear people's opinions on this

**Comment by reez** [comment]
> Not in Nashville right now, but a topic I think is relevant: Are BTC spot ETFs at high risk because Coinbase is listed as custodian for almost all the ETFs? Should the custodians be more 'decentralized'? Is it a big problem that Coinbase is effectively 'running the show'? Or is this okay? Would love to hear people's opinions on this

Great suggestion and thoughts/questions for the discussion!

**Comment by notmandatory** [comment]
@willowenss does this article cover the issue you're concerned about? 

**News**

[CoinDesk: "The Biggest Bitcoin ETF Threat No One Is Talking About"](https://www.coindesk.com/consensus-magazine/2024/01/11/the-biggest-bitcoin-etf-threat-no-one-is-talking-about/)

**Comment by willowenss** [comment]
@notmandatory yes that’s it!! Super good read - thanks for sharing. Would love to hear y’alls thoughts on that. Sadly I cannot attend as I’m on the opposite side of the planet 😅
